---
- name: create backend docker image
  hosts: localhost
  tasks:
  - name: run docker command        
    command: sudo docker build -t backend:{{image_id}} /tmp/devops-s3/target/
  - name: run tag command   
    command: sudo docker tag backend:{{image_id}} naveen24788/backend:{{image_id}}
  - name: run docker login command  
    command: sudo docker login --username naveen24788 --password 46c79302-1968-4a60-af09-65742d5fcf31
  - name: run docker push
    command: sudo docker push naveen24788/backend:{{image_id}}